#!/usr/bin/env bash
# Find the real bat.
HERE="$(cd "$(dirname "$0")" && pwd)"
while read -d ':' -r dir; do
	if [[ "$dir" == "$HERE" ]]; then continue; fi
	if [[ -f "${dir}/bat" ]]; then
		exec "${dir}/bat" "$@" --theme="Monokai Extended"
	fi
done <<< "$PATH"
